name: sandboxnotion
description: Cross-platform productivity app with modular sandbox UI, combining Calendar, Tasks, Notes, Whiteboards, and Flash-cards, powered by Firebase and OpenAI.
version: 1.0.0+1
repository: https://github.com/amassouya/SandboxNotion

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cloud_functions: ^4.5.8
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.9
  firebase_app_check: ^0.2.1+8
  flutterfire_ui: ^0.4.3+20

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Navigation
  go_router: ^13.0.1

  # UI components
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  animations: ^2.0.8
  flutter_drawing_board: ^0.4.4+2
  flutter_quill: ^8.6.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.1
  flutter_colorpicker: ^1.0.3
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  flutter_markdown: ^0.6.18+2
  table_calendar: ^3.0.9
  timeline_tile: ^2.0.0
  confetti: ^0.7.0

  # Drag and drop
  flutter_reorderable_grid_view: ^5.0.0
  reorderables: ^0.6.0
  drag_and_drop_lists: ^0.3.3

  # OpenAI integration
  http: ^1.1.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  mime: ^1.0.4
  uuid: ^4.2.1
  record: ^5.0.1
  just_audio: ^0.9.36
  flutter_dotenv: ^5.1.0

  # Payment
  in_app_purchase: ^3.1.11
  pay: ^1.1.2
  in_app_purchase_storekit: ^0.3.7+1
  in_app_purchase_android: ^0.3.0+15

  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  intl: ^0.18.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.2+1
  collection: ^1.18.0
  equatable: ^2.0.5
  async: ^2.11.0
  rxdart: ^0.27.7
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.2.0
  app_settings: ^5.1.1
  flutter_keyboard_visibility: ^5.4.1
  video_player: ^2.8.1
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.3
  mocktail: ^1.0.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.13.0
  
  # Linting
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

# Flutter configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
    - assets/env/
    - .env
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Platform-specific configurations
flutter_native_splash:
  color: "#4C7AF9"
  image: assets/images/splash.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#4C7AF9"
    theme_color: "#4C7AF9"
