// File generated by FlutterFire CLI.
// This file contains Firebase configuration options for different platforms.
// IMPORTANT: Replace these placeholder values with your actual Firebase configuration!
// To generate this file properly, use: flutterfire configure --project=sandboxnotion

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the SandboxNotion app.
///
/// REPLACE THESE PLACEHOLDER VALUES with the actual configuration from your
/// Firebase project. You can generate this file using the FlutterFire CLI:
/// ```
/// flutterfire configure --project=sandboxnotion
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // REPLACE WITH YOUR ACTUAL CONFIGURATION VALUES
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:889983767784:web:ee1505262ed22221a4655d',
    messagingSenderId: '889983767784',
    projectId: 'sandboxnotion',
    authDomain: 'sandboxnotion.firebaseapp.com',
    storageBucket: 'sandboxnotion.appspot.com',
    measurementId: 'G-M3Q4PS16KG',
  );

  // REPLACE WITH YOUR ACTUAL CONFIGURATION VALUES
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:889983767784:android:ee1505262ed22221a4655d',
    messagingSenderId: '889983767784',
    projectId: 'sandboxnotion',
    storageBucket: 'sandboxnotion.appspot.com',
  );

  // REPLACE WITH YOUR ACTUAL CONFIGURATION VALUES
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:889983767784:ios:ee1505262ed22221a4655d',
    messagingSenderId: '889983767784',
    projectId: 'sandboxnotion',
    storageBucket: 'sandboxnotion.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.sandbox.notion',
  );

  // REPLACE WITH YOUR ACTUAL CONFIGURATION VALUES
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:889983767784:ios:ee1505262ed22221a4655d',
    messagingSenderId: '889983767784',
    projectId: 'sandboxnotion',
    storageBucket: 'sandboxnotion.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.sandbox.notion.RunnerTests',
  );
}
